### ISSUE TITLE
Add `#include <stdlib.h>` to examples

### ISSUE THREAD

**Issue by RikkiButler20** [pmodels/bolt#100]
I get this warning when I try to compile any of the examples.
```
 warning: incompatible implicit declaration of built-in function 'malloc'
     double *a = (double *)malloc(sizeof(double)*num);
```
I was able to fix it by adding `#include <stdlib.h>` to the examples

**Comment by shintaro-iwasaki** [comment]
Thanks, @RikkiButler20! I will fix the example.

**Comment by shintaro-iwasaki** [comment]
Fixed. Thank you for reporting an issue!
