### ISSUE TITLE
BOLT build fails on ppc64le

### ISSUE THREAD

**Issue by shintaro-iwasaki** [pmodels/bolt#48]
This issue was reported in https://github.com/spack/spack/issues/15550

**Comment by eugeneswalker** [comment]
I am at the University of Oregon helping to maintain a publicly accessible cache of E4S Spack packages. We would love to include `bolt` for `ppc64le` in our cache, but it is not building right now.  Thanks for taking a look!

**Comment by shintaro-iwasaki** [comment]
@eugeneswalker #57 should fix the compilation bug you reported (compilation errors in `kmp_lock.cpp`).
It worked on ppc64le (POWER 9, with a Summit-like configuration) with GCC 4.8, but I believe it should be compiled with other GCC/Clang compilers too.

Thank you for reporting the problem!
